{% set name = "chalk" %}
{% set version = "3.0.0" %}
{% set sha256 = "2202478ed680553ae272b8063c282f04c5dbac3378eb0396ba93f847a0a20871" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chalk/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g chalk
  requires:
    - nodejs
   

about:
  home: https://github.com/chalk/chalk
  license: MIT
  license_family: MIT
  license_file: license
  summary: 'Terminal string styling done right'
  description: |
    Terminal string styling done right
  doc_url: https://github.com/chalk/chalk
  dev_url: https://github.com/chalk/chalk

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
