{% set name = "chalk" %}
{% set version = "2.4.2" %}
{% set sha256 = "33b6abb8847ca83fa10881c4cd37a50682871f0e67bdad4d23e6ca6b39a2c19d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chalk/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: |
    tgz=$(npm pack)
    npm install -g $tgz

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g chalk
  requires:
    - nodejs
   

about:
  home: https://github.com/chalk/chalk
  license: MIT
  license_family: MIT
  license_file: license
  summary: 'Terminal string styling done right'
  description: |
    Terminal string styling done right
  doc_url: https://github.com/chalk/chalk
  dev_url: https://github.com/chalk/chalk

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
