{% set name = "chalk" %}
{% set version = "2.3.1" %}
{% set sha256 = "7ed92535fe83409d80aae79983dd8e974b3c97f4e316d80d9d96655754113d4d" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/chalk/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: generic
  script: npm install -g .

requirements:
  build:
    - nodejs
  
test:
  commands:
    - npm list -g chalk
  requires:
    - nodejs
   

about:
  home: https://github.com/chalk/chalk
  license: MIT
  license_family: MIT
  license_file: license
  summary: 'Terminal string styling done right'
  description: |
    Terminal string styling done right
  doc_url: https://github.com/chalk/chalk
  dev_url: https://github.com/chalk/chalk

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
