travis:
  secure:
    BINSTAR_TOKEN: KnuIqK3dg/rz/9X7+UvXnVcUBqwluWFyVnWnVQfKxmASwkaUiPnXaJgF2LivEy5OvgDSyal6RVJsbUgi2dshZaGuGgGnjfNOf1b6+FknqNEp5TX49W5oDMaC7/FCepgIGiGh3pEGjAT8We5sVy3JdjSG9UkAtE0GgRe0DjMJjMwtrJeBCmjV3UnCDq5yvbYCP+UQYKXNgZRxF4EZQY2Xsr+dwjLITyDkwG3Q0PbjCP1q9uStT1iwD1Bq/5cUNvvRtbTVQEKdXvC5OEngCreDa5wIlLKgmZAO9qxUH775Mt1413ryr2oJ/6LtX3ZEDR7WXkWAjVLIZBH5a7SsO6BxTX0tgpL99i+fEEg6vbU8aHkC3D/U968U/DWt21dJDHZCanslahILJst+vGvLt8mnJIvVvEhdiM794vX+tS0FEHjaL1PSDkgIfUcKz93b+lCBcUonxuvFGRkFou9tTtNN5S+bPnbAz9/TsdPxa4CHWQvSX7s3/OsEXrYYTu57ZKldyTDBzAUFppI2qqliI/KhtSMRgxZCEPBR3Sx8/mKfIFnQV8a93ONzVIHg7g9OjCUIx9yw6wIAalbwsl1bZ0Fn9MiZENnpCpJVapWOFqBTVqZkQucK/FGv9pJdsT2L+H1doeZa7GMAaJXoURnyT8ktKMJ9HQGTp+lnF6Y5vGzXhbI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
