travis:
  secure:
    BINSTAR_TOKEN: oblSy1qGd6dZEgqBVBoNbzwuSSux/m+rt+dM4Ut+2nloN+5mRjmf5Le+w2BvyrmgXi09WfsKSyawIK7C0oqKlhFJN333NqXo4PGNKsVBlIscdxULi0RfrDeEMW97+OQ/R7E5Eo6tspBSbHg2HHUAW6rvxQ/iY7W0JosAsrQUI4tTF/IbUuQ8nyBdiyaheAZjyTRmJcMXw/kY74ceZYcs2Po+3lURTHKTQ7qQ6U35FWCqZ1gHnWJqox/l2Pi3kZcAauj3gQ/jrccwjgymsx+S6Df3Rcb/z7fuckKIu3J3quDPfkj9dEwtokpZ3gcsF6qXcdjMCu1nW8x/pHy7WdoOgloaRizAoVVav2YYBX9Wyq0w6513K+wr/YPtHbe2AZ8ItC8lPtC6iVfmNOHsyWnx/O1paqPywnhJX6LdibrcyDUEBAeT1EbOVeAJ2fCAXJF+tJ/8oP9dsMBOclt1WfsKSh9C2+UiFSPYbCJ4qOxPVzA/HlU5HGmo8oyTQ7GulD3pFIj6nx9JJaR+xHaIWoy7fg8IbowJv233lteDcqgS8pzH0Lr2m4ppVRklcdDC+VyLpGr7wtcJDei5agdeqxNWbCpq/ZMW+HJ31tSAhybu9/jD+RRTYfPoM0uGNO5WB9rguFb+Lsc93BencM2rkdhxi6Gdp/ERWsyad2tOerRnt94=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
